import = ["~/.config/alacritty/themes/alacritty-theme/themes/tokyo-night.toml", "~/.config/alacritty/fonts.toml"]
live_config_reload = true

colors.draw_bold_text_with_bright_colors = false

[cursor]
unfocused_hollow = false
[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = false
#multiplier = 3
opacity = 1

[window.dimensions]
columns = 82
lines = 23

[window.padding]
x = 0
y = 0
